package.json
vscode-extensions/inscription/extension/package.json
vscode-extensions/inscription/extension/src/inscription-extension.ts
vscode-extensions/process-editor/extension/package.json
vscode-extensions/process-editor/extension/src/ivy-editor-provider.ts
vscode-extensions/process-editor/extension/src/ivy-extension.ts
vscode-extensions/process-editor/extension/src/ivy-vscode-connector.ts
vscode-extensions/process-editor/extension/webpack.config.js
vscode-extensions/process-editor/webview/package.json
vscode-extensions/process-editor/webview/src/app.ts
vscode-extensions/process-editor/webview/src/ivy-diagram-widget.ts
vscode-extensions/process-editor/webview/src/open-inscription/open-inscription-handler.ts
yarn.lock

- adapt to https://github.com/eclipse-glsp/glsp-vscode-integration/pull/36

XIVY-11498 raise @eclipse-glsp to 1.1.0-RC09

---

vscode-extensions/inscription/extension/css/inscription-editor.css
vscode-extensions/inscription/webview/src/index.css

- Remove vscode variables, use colors of inscription view (same as process editor)

Fix colors of inscription view in vscode

---

vscode-extensions/inscription/extension/css/inscription-editor.css
vscode-extensions/inscription/extension/src/inscription-view-provider.ts
vscode-extensions/inscription/webview/package.json
vscode-extensions/inscription/webview/src/index.tsx
vscode-extensions/process-editor/webview/css/colors.css
yarn.lock

@ivy-lli note that the inscription view is not yet in sync for high contrast dark, see
where can that be solved?

XIVY-11458 manually sync VS Code theme Monaco

---

vscode-extensions/config-editor/webview/package.json
vscode-extensions/inscription/extension/package.json
vscode-extensions/inscription/webview/package.json
vscode-extensions/inscription/webview/src/index.tsx
vscode-extensions/process-editor/webview/package.json
yarn.lock

fix: add QueryClientProvider & pass pmv and app

---

vscode-extensions/config-editor/extension/package.json
vscode-extensions/config-editor/extension/src/editor-provider.ts

- remove command from panel
- create new variables.yaml under /config

new variables.yaml command improvement

---

build/Dockerfile
package.json
yarn.lock

also raise:
- @types/node
- eslint
- typescript

Move from node 16 to node >=18

---

vscode-extensions/base/src/commands.ts
vscode-extensions/engine/extension/package.json
vscode-extensions/engine/extension/src/engine-api.ts
vscode-extensions/engine/extension/src/engine-manager.ts
vscode-extensions/engine/extension/src/index.ts
vscode-extensions/project-explorer/extension/src/ivy-project-explorer.ts
vscode-extensions/project-explorer/extension/src/ivy-project-tree-data-provider.ts

- add IvyEngineManager
- new requests for init- deploy- and build ivy projects
- show progress notification when client sends workspace request to engine
- new commands to open dev wf ui and engine cockpit

XIVY-12269 adapt to workspace endpoints

---

vscode-extensions/base/src/commands.ts
vscode-extensions/engine/extension/src/engine-manager.ts
vscode-extensions/project-explorer/extension/src/ivy-project-explorer.ts
vscode-extensions/project-explorer/extension/src/ivy-project-tree-data-provider.ts

project files were sorted before ;)

XIVY-12269 fix project sorting: hold project directories

---

vscode-extensions/config-editor/extension/package.json
vscode-extensions/engine/extension/package.json
vscode-extensions/process-editor/extension/package.json
vscode-extensions/project-explorer/extension/package.json

streamline command title/category

---

vscode-extensions/engine/extension/package.json
vscode-extensions/engine/extension/src/build/maven.ts
vscode-extensions/engine/extension/src/engine-manager.ts
yarn.lock

using multiple workspaces should also be supported now

make build all projects work & respect multi-module projects

---

src/engine/build/maven.ts

No 'Progress (1): 4.1/17 kB' outputs

XIVY-12269 Use batch mode for nicer output

---

package.json
src/base/commands.ts
src/engine/api/engine-api.ts
src/engine/api/request.ts
src/engine/engine-manager.ts
src/index.ts
src/project-explorer/ivy-project-explorer.ts
src/project-explorer/ivy-project-tree-data-provider.ts
src/project-explorer/new-process.ts
src/project-explorer/new-project.ts

& add submenu for adding Business Process, Callable Sub,...

XIVY-11752 add create project command

---

src/engine/build/maven.ts
src/engine/engine-manager.ts
src/project-explorer/new-process.ts

- set ivy.engine.version for maven build
- init project, create init process and build&deploy on project creation

XIVY-11752 create project improvements

---

src/process-editor/ivy-vscode-connector.ts

as long as no severy `NONE` messages appears

Handle all messages, hide model loading

---

package.json
src/engine/build/maven.ts
src/engine/engine-manager.ts
src/process-editor/ivy-editor-provider.ts
src/project-explorer/ivy-project-explorer.ts
src/project-explorer/ivy-project-tree-data-provider.ts
src/project-explorer/new-process.ts
src/project-explorer/new-project.ts
src/project-explorer/utility.ts

- add delete tree item shortcut
- ask user before permanently delete
- add welcome view for project explorer
- close process editor if file gets deleted
- combine process name and namespace user input
- create new process/project -> validate user input
- support create project with multiple workspaces

XIVY-11752 various project explorer related improvements

---

package.json
playwright/tests/engine.test.ts
playwright/tests/page-objects/explorer-view.ts
playwright/tests/page-objects/page-object.ts
playwright/tests/project-explorer.test.ts
playwright/tests/workspaces/default/.vscode/settings.json
playwright/tests/workspaces/multi-project/.vscode/settings.json
playwright/tests/workspaces/multi-project/exclude-me/.project
playwright/tests/workspaces/no-engine/.vscode/settings.json
playwright/tests/workspaces/no-project/.vscode/settings.json
src/base/configurations.ts
src/engine/build/maven.ts
src/engine/engine-manager.ts
src/project-explorer/ivy-project-tree-data-provider.ts

& remove ivy container
this configuration name change will break code.ivyteam

XIVY-12783 exlcude pattern for project detection

---

lerna.json
playwright/package.json
webviews/config-editor/package.json
webviews/process-editor/package.json

Raise version to 11.3.0-SNAPSHOT

Raise version to 11.3.0-SNAPSHOT

---

webviews/config-editor/package.json
webviews/process-editor/package.json
yarn.lock

Should run next time automatically without problems ...

Raise deps manually to 11.3

---

extension/src/engine/build/maven.ts

building demo-projects fails with `process-test-classes` so I have changed it to `package`

XIVY-12892 fix maven build

---

extension/assets/.devcontainer/devcontainer.json

you can check it out here https://github.com/axonivy-market/demo-projects/tree/codespace-rdy

run engine after starting devcontainer

---

extension/package.json
extension/src/index.ts
extension/src/messenger.ts
extension/src/process-editor/ivy-editor-provider.ts
extension/webviews/process-editor/package.json
extension/webviews/process-editor/src/app.ts
extension/webviews/process-editor/src/ivy-diagram-widget.ts
extension/webviews/process-editor/src/start/action.ts
yarn.lock

First use of vscode-messenger for communication between extension and webview.

XIVY-13138 use vscode-messenger

---

extension/src/base/commands.ts
extension/src/engine/api/project-request.ts
extension/src/inscription-action-handler.ts
extension/src/project-explorer/ivy-project-explorer.ts
extension/src/project-explorer/new-process.ts
extension/src/project-explorer/new-user-dialog.ts
extension/src/websocket-forwarder.ts
extension/webviews/process-editor/src/ivy-diagram-widget.ts
extension/webviews/process-editor/src/message-writer.ts

depends on https://github.com/axonivy/core/pull/4801
After creating a process/hd via inscription, the configuration of the call target is not updated correctly. It seem to be a timing issue, I will check that.

XIVY-13143 handle new process and new hd actions triggered by inscription

---

extension/src/process-editor/ivy-editor-provider.ts
extension/webviews/process-editor/src/app.ts
extension/webviews/process-editor/src/context-menu/di.config.ts
extension/webviews/process-editor/src/startup.ts

- Provide empty implementation of context menu service
- Do not re-use WebviewReadyNotification from GLSP but use custom one

Fix warnings and errors on diagram opening

---

extension/src/inscription-action-handler.ts
extension/src/inscription-view/open-page.ts
extension/webviews/process-editor/package.json
yarn.lock

XIVY-12913: Catch and implement openPage-action

---

extension/package.json
extension/src/base/build-manifest.ts
extension/src/process-editor/ivy-editor-provider.ts
extension/webviews/process-editor/index.html
extension/webviews/process-editor/package.json
extension/webviews/process-editor/src/app.ts
extension/webviews/process-editor/src/index.css
yarn.lock

- Adapt to new structure with ivy-tool-bar being outside of diagram
- Read HTML file from source and adapt instead of re-creating it
- Slightly improve editor worker location handling in webview

Align VS Code process editor with improved structure

---

extension/package.json
extension/src/base/commands.ts
extension/src/base/webview-nonce.ts
extension/src/engine/engine-manager.ts
extension/src/form-editor/form-editor-provider.ts
extension/src/index.ts
extension/src/websocket-forwarder.ts
extension/webviews/form-editor/.eslintrc.cjs
extension/webviews/form-editor/css/colors.css
extension/webviews/form-editor/index.html
extension/webviews/form-editor/package.json
extension/webviews/form-editor/src/index.tsx
extension/webviews/form-editor/src/message-reader.ts
extension/webviews/form-editor/src/message-writer.ts
extension/webviews/form-editor/tsconfig.json
extension/webviews/form-editor/vite.config.ts
vscode-extensions.code-workspace
yarn.lock

Based on core PR: https://github.com/axonivy/core/pull/5329

XIVY-13641 Add Form Editor webview editor 

---

extension/src/editors/form-editor/webview-communication.ts
extension/src/project-explorer/ivy-project-explorer.ts

& update file watcher so that `*.f.json` changes are ignored (negation is not supported...)

XIVY-13807 build form: modify method saveData to saveDataAndBuild

---

.ivy/raise-build-plugin-version.sh
.ivy/raise-version.sh
extension/src/engine/build/maven.ts
extension/webviews/config-editor/package.json
extension/webviews/form-editor/package.json
extension/webviews/process-editor/package.json
playwright/tests/form-editor.test.ts
playwright/tests/page-objects/variables-editor.ts
playwright/tests/workspaces/multi-project/prebuiltProject/.settings/ch.ivyteam.ivy.designer.prefs
playwright/tests/workspaces/multi-project/prebuiltProject/ProcessOutline.p.json
playwright/tests/workspaces/multi-project/prebuiltProject/Validation.p.json
playwright/tests/workspaces/multi-project/prebuiltProject/pom.xml
yarn.lock

- Raise engine version to v11.4.0
- Fix Variables / Form editor tests
- Add raise-build-plugin-version script
- Improve raise-version script, so it also raises the ivy engine version in maven.ts

Fix builds for newest artifacts/versions

---

build/integration/Jenkinsfile
build/integration/base/Jenkinsfile
build/integration/base/build.sh
build/integration/openvscode-server/Dockerfile
build/integration/openvscode-server/Jenkinsfile

https://jenkins.ivyteam.io/job/vscode-extensions_playwright-base-docker-image/

rename base images

---

extension/webviews/config-editor/package.json
extension/webviews/form-editor/package.json
extension/webviews/process-editor/package.json
package-lock.json

Reverts axonivy/vscode-extensions#359

Revert "Raise dependencies version to 13.1.0-SNAPSHOT"

---

extension/webviews/config-editor/package.json
package-lock.json
package.json

fixes https://jenkins.ivyteam.io/job/vscode-extensions/job/master/7583/console

fix react peer deps issue

---

playwright/tests/fixtures/page.ts
playwright/tests/inscription-view.test.ts
playwright/tests/page-objects/page-object.ts
playwright/tests/process-animation.test.ts
playwright/tests/variables-editor.test.ts

related to https://github.com/axonivy/core/pull/7536

stabilize tests

---

extension/src/engine/api/axios-error-handler.ts
extension/src/engine/api/engine-api.ts
playwright/tests/create-process.test.ts

XIVY-15504 show backend (validation) errors to user

---

extension/package.json
extension/src/base/commands.ts
extension/src/engine/animation.ts
extension/src/engine/api/engine-api.ts
extension/src/engine/api/generated/openapi-default.ts
extension/src/engine/api/generated/openapi-dev.ts
extension/src/engine/api/jsonrpc-protocol.ts
extension/src/engine/api/jsonrpc.ts
extension/src/engine/engine-manager.ts
extension/src/project-explorer/ivy-project-explorer.ts
extension/webviews/config-editor/package.json
extension/webviews/form-editor/package.json
extension/webviews/process-editor/package.json
package-lock.json
playwright/tests/engine.test.ts
playwright/tests/page-objects/process-editor.ts
playwright/tests/process-animation.test.ts

& enable animation per default

XIVY-14432 animation fix & reset animation command

---

extension/package.json
package-lock.json
package.json
webviews/config-editor/package.json
webviews/form-editor/package.json
webviews/process-editor/package.json

move deps that get updated automatically to the root

fix build: avoid nested node_modules

---

package-lock.json
package.json

Reverts axonivy/vscode-extensions#450

Revert "Update dependency typescript to v5.8.2 (master)"

---

.github/workflows/openvscode-server-integration.yml
build/integration/openvscode-server/Jenkinsfile

slightly easier to re-use and copy from ... since we do not restate the version again and again.

simplify openvscode-server fetcher

---

scripts/download-engine.cts

fix engine download

---

.github/workflows/electron-integration.yml
.github/workflows/openvscode-server-integration.yml

fixes: [Workflow does not contain permissions](https://github.com/axonivy/vscode-extensions/security/code-scanning/8)

disable github permissions

---

extension/package.json
package-lock.json
package.json
vscode-designer.code-workspace
webviews/browser/package.json
webviews/cms-editor/package.json
webviews/cms-editor/src/index.tsx
webviews/dataclass-editor/package.json
webviews/dataclass-editor/src/index.tsx
webviews/form-editor/package.json
webviews/form-editor/src/index.tsx
webviews/process-editor/package.json
webviews/process-editor/src/app.ts
webviews/process-editor/src/startup.ts
webviews/variable-editor/package.json
webviews/variable-editor/src/index.tsx
webviews/webview-common/package.json

https://github.com/axonivy/vscode-designer/pull/557

Scope all packages > R13.1

---

extension/package.json

now you can switch to pre release

make 13.2 pre release

---

.vscode/tasks.json
extension/package.json
extension/webpack.config.js

based on https://github.com/axonivy/vscode-designer/pull/532

XIVY-16971 text-based process model git diff

---

.devcontainer/devcontainer.json
.github/workflows/electron-integration.yml
.github/workflows/openvscode-server-integration.yml
extension/assets/.devcontainer/devcontainer.json
extension/src/index.ts

I have merged this change into master instead of 13.1... https://github.com/axonivy/vscode-designer/pull/558

use engine 13

---

lerna.json
package-lock.json
package.json

Change to lerna-lite

---

extension/package.json
package-lock.json
package.json

lock file maintenance procedure:
- npm run update:axonivy:next
- delete package-lock.json
- npm install
- npm ddp
with the fixtures I have made, this procedure should currently be reproducible.

lock file maintenance and make it reproducible

---

extension/src/engine/ws-client.ts
playwright/tests/runtime-log.spec.ts

now it looks like this
and its possible to filter after the log levels

XIVY 16480 RuntimelogOutputImprovements
